[package]
name = "xtb-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "^1.0.57"

[dev-dependencies]
rstest = "^0.18.2"
rstest_reuse = "^0.6.0"
serde = "^1.0.197"
serde_json = "^1.0.114"
